[spotify]
"EP93ï½œç•¶ç†ç§‘å­¸éœ¸å­¸äººé¡åœ– ft.Astor" = "https://open.spotify.com/episode/3mUr0zgVN4evDHQt5Bwwte"
"EP92ï½œä¸¹éœ–ç™‚å®¤ å†è¦‹å¤©ä½¿ ft.Bonnie" = "https://open.spotify.com/episode/5v3yA7fbM4lB4PmRmgJvCP"
"EP91ï½œéŠ€æ²³è¯é‚¦è¦ªè‡¨" = "https://open.spotify.com/episode/1s4ylnviVLwvoqHl45evTS"
"EP90ï½œä½ çš„å¤©ä½¿å¥½å¤¥ä¼´ æ…ˆæ‚²å¤©ä½¿è–åœ˜" = "https://open.spotify.com/episode/67Efwm3FDM8cOEQ2o6rNtc"
"EP89ï½œéˆæ€§æ­æ´²æ—…è¡Œä¹‹å¥³å·«åˆ°åº•åœ¨å“ªè£¡" = "https://open.spotify.com/episode/4O63pEbd40QTOvrmZtkGDP"
"EP88ä¸¹éœ–èŠå®¤02ï½œå¥‡å¹»æ—…ç¨‹" = "https://open.spotify.com/episode/7DvXXu1QnaGQUVJmDlteuz"
"EP87ï½œä¾†çœ‹çœ‹ç´«å¾®ç©ä»€éº¼ ft.å¤§è€•è€å¸«" = "https://open.spotify.com/episode/2SRCfiOb2U9T0AMDe5vzcC"
"EP86ï½œå®¶æ—æ’åˆ—" = "https://open.spotify.com/episode/097M1DKqLMygXi15QeDJdM"
"EP85ï½œä»Šå¤©ä¾†å–åå­—å›‰ï¼" = "https://open.spotify.com/episode/5afTAtmPzqpmXcJGrHvGmC"
"EP84ä¸¹éœ–èŠå®¤01ï½œä¾†è‡ªå¦ä¸€å€‹ä¸–ç•Œçš„æ•…äº‹" = "https://open.spotify.com/episode/19KCOLvTTSmLIzlIgHGP0J"
"EP83ï½œLetâ€™sç©ç©é™°é™°å¾·" = "https://open.spotify.com/episode/6Q2g9UDfH3COetNwrRVke3"
"EP82ï½œç«çš„é­”æ³• ft.æ±Ÿæ±Ÿè€å¸«" = "https://open.spotify.com/episode/53E6XbUnDVgJp31Pb4myzK"
"EP81ï½œç´«è‰²ç«ç„°2.0" = "https://open.spotify.com/episode/71fbwvVY2aRWZGYXoX0pCX"
"EP80ï½œè®“è‰¾è‰çµ²ä¾†æ•™ä½ ç”Ÿå‘½éˆæ•¸" = "https://open.spotify.com/episode/39uoCooT3PFFpdnOJNGEsW"
"EP79ï½œèŠ³é¦™ç™‚æ³•å¤©åä¾†äº† ft.GINA è¨±æ€¡è˜­" = "https://open.spotify.com/episode/5YxFrHuxFo2Gtj3nkjkX7r"
"EP78ï½œé–’èŠé»ƒé‡‘ç´€å…ƒ" = "https://open.spotify.com/episode/4DJUzYKxwKYzAfHmMi28AX"
"éœå¿ƒé Œç¼½ ft. é Œç¼½ç™‚ç™’å¸« Ashley æ„›å¸Œ" = "https://open.spotify.com/episode/18fjV63djYen1lGfJJ3K0e"
"EP77ï½œé Œç¼½å¸« ft. é Œç¼½ç™‚ç™’å¸« Ashley æ„›å¸Œ" = "https://open.spotify.com/episode/7BDny3gik3vspm68FLeLMR"
"EP77ï½œé Œç¼½å¸« ft.Ashley" = "https://open.spotify.com/episode/7BDny3gik3vspm68FLeLMR"
"EP76ï½œé–‹æ‚Ÿä¸ƒè„ˆè¼ª" = "https://open.spotify.com/episode/0IzfQc9Sa2135U0Cvzk4aq"
"EP75ï½œä¸æƒ³é•·å¤§çš„äºº" = "https://open.spotify.com/episode/5HlyGp7V7M4wTGTLXXqKv2"
"EP74ï½œè·Ÿæ¯å¨˜å€‘è«‹å®‰" = "https://open.spotify.com/episode/7lLUnzf37bvjsnt1vi23xb"
"EP73ï½œé–’èŠé›æ¹¯" = "https://open.spotify.com/episode/5UTY6jprGilr0ceDFxMFPk"
"EP72ï½œè²¡ç¥çºŒé›†" = "https://open.spotify.com/episode/7pClMuB3hHfTf3A6dBNwkC"
"EP71ï½œå§»ç·£é‚„çœ‹æ¥­åŠ›å¹³è¡¡?!" = "https://open.spotify.com/episode/5xgtg1mlfEsZNaM0pkqb3A"
"EP70ï½œå‘½é‹è¨­è¨ˆç³»ä¸»ä»»ä¾†äº† feat.ç°¡å°‘å¹´" = "https://open.spotify.com/episode/6DlXCPEUtx5FBqIuVJWvMC"
"EP69ï½œæˆ‘å€‘å»å¯µç‰©æºé€šäº†ï¼ft.é‡‘å¦®ã€å°èƒ–" = "https://open.spotify.com/episode/3WRd8AbMLur459Fu3TZmbP"
"EP68ï½œéˆé­‚è¡¨æ¼”èª² ft.æœ±å®ç« è€å¸«" = "https://open.spotify.com/episode/6Fmw4FILBNE3F9Bn9f82Wh"
"EP67ï½œè–å¡”åº«ç‘ªæ‹‰" = "https://open.spotify.com/episode/4xgeFhAIj2Ivt0oxihtSQt"
"EP66ï½œå¥½é¢ç›¸ ft.é‡Œæ°‘æœå‹™ä¸­å¿ƒ" = "https://open.spotify.com/episode/7HaUzpSJldQGbCEd31VX5w"
"EP65ï½œé™¤å¤•ç‰¹åˆ¥ç¯€ç›® ft.å–„åµæ…¶å¥³" = "https://open.spotify.com/episode/52kTj0iUdRZ9FvPMRjduDD"
"EP64ï½œæ‰¹é‡ç”Ÿç”¢ã®è²´äºº" = "https://open.spotify.com/episode/5IvlYXySYhrUOTg3BvIibr"
"EP63ï½œç¥ä»™é›œè²¨æ®¿" = "https://open.spotify.com/episode/3U7sCh1Ka9zVOCwmRTBV7B"
"EP62ï½œæ±æ–¹éˆæ•¸" = "https://open.spotify.com/episode/5QUxWXYFv3mqmpBRtOblWu"
"EP61ï½œå¥—æˆ¿è‡¥å®¤é¢¨æ°´" = "https://open.spotify.com/episode/2kkhqJadJiVdzZNl285aOU"
"EP60ï½œ2024 ä½ æƒ³è½ä»€éº¼ä¸»é¡Œå‘¢ï¼Ÿ" = "https://open.spotify.com/episode/3Qi3TpL1VGj19z235GZWPG"
"EP59ï½œå‚¬çœ  ft.è«å½¼" = "https://open.spotify.com/episode/2DPwGfUTVEWCiZ2rDUSoFB"
"EP58ï½œä¸¹å…¬è§£å¤¢å®Œçµ" = "https://open.spotify.com/episode/2mB79dipI0lws9z85mNKFj"
"EP57ï½œäººé¡åœ– feat.è·¯å˜‰æ€¡" = "https://open.spotify.com/episode/5FqaSyZiLOIVFUCvLCvLDK"
"EP56ï½œä¸¹å…¬è§£å¤¢ 4" = "https://open.spotify.com/episode/6oxzmBiazmbtg3TH3PpOIc"
"EP55ï½œé«˜æˆ‘2.0 feat.ä¸€å’ª" = "https://open.spotify.com/episode/0qDCQW9SiWoQziFDYblCjc"
"EP54ï½œé¢¨æ°´å•ç­”é›†" = "https://open.spotify.com/episode/65c4iOyJFWbMXN3W4P78gu"
"EP53ï½œå®¢å»³é¢¨æ°´" = "https://open.spotify.com/episode/1fwx86z8QOWNBrTis7Wmrk"
"EP52ï½œéˆæ€§å‘¨æ­²ï½œç¥ä»™è£œç¿’ç­ä¸€æ­²äº†ï¼" = "https://open.spotify.com/episode/4QV7DjEx6VtPZejQRhYSZD"
"EP51ï½œæ ¡åœ’æš´å¾’ï¼" = "https://open.spotify.com/episode/526ftJr4d6C3UuWK3fqj1I"
"EP50ï½œæšå‡å›‰ï¼" = "https://open.spotify.com/episode/7zuW62A3izYnklS2XPLKRu"
"EP49ï½œéˆæ“ºæ•²é–€ç­" = "https://open.spotify.com/episode/7tkFn2TImaZJyF4yh4Ga5d"
"EP48ï½œå¥‡è¹Ÿä¾†æ•²é–€" = "https://open.spotify.com/episode/0O5UbjMNrpCFwPkS5yLe5V"
"EP47ï½œä¸¹å…¬è§£å¤¢ä¸‰" = "https://open.spotify.com/episode/3YOs3MjpownSkeJVM1A3yf"
"EP46ï½œæ“´å¤§ç™‚ç™’æ³• ft.ç“¦é‡" = "https://open.spotify.com/episode/60cYCzYiW2PRCtNbnfb5Fy"
"EP45ï½œéˆæ“ºå¹¼å¹¼ç­" = "https://open.spotify.com/episode/0iINl2lIghRYt0AN9jS6ut"
"EP44ï½œWHY?! ä¸¹å…¬è§£å¤¢ç¬¬äºŒé›†" = "https://open.spotify.com/episode/2ITjroLLFxdIW6fxC8lozn"
"EP43ï½œæ¬¡å…ƒç¶­åº¦ x å¹³è¡Œå®‡å®™" = "https://open.spotify.com/episode/0hvZTTSFDwUoHNr8DN577K"
"EP42ï½œåˆ†é›¢æ„Ÿ ft.å°å…‰" = "https://open.spotify.com/episode/6f1VNeOiLjJyGVEfMllNbR"
"EP41ï½œé›™ç”Ÿç«ç„°" = "https://open.spotify.com/episode/5qEB6RyBx0e1jsGAupXaHa"
"EP40ï½œWHY?! ä¸¹å…¬è§£å¤¢ç¬¬ä¸€é›†" = "https://open.spotify.com/episode/1iKkrMtuf8WjpXk1H6w7tS"
"EP39ï½œé¬¼æœˆ ft.è¬å¯¶" = "https://open.spotify.com/episode/3JZbvWZR8wBuAbC9fV0eUo"
"EP38ï½œå®ˆè­·å¤©ä½¿ 4niï¼Ÿï¼" = "https://open.spotify.com/episode/7fwQ3G1L5GAwiXCUCoyfq6"
"EP37ï½œä¸å°ˆæ¥­å¡”ç¾…è‡ªå­¸ä¹‹è¡“ ft. ReRe" = "https://open.spotify.com/episode/7bjH8S4eqrdkgrNi2NOU7i"
"EP36ï½œäº”è¡Œè£œèª² ft. ReRe" = "https://open.spotify.com/episode/2gxjgMsTRBq1YLt4rFmTIz"
"EP35ï½œä¸¹ä¸¹å»å­¸å¯µç‰©æºé€šï¼ft.é‡‘å¦®ã€å°èƒ–" = "https://open.spotify.com/episode/7g5tS8zgfBVdAsxcZPU0x3"
"EP34ï½œæ˜Ÿåº§ä¸æº–ï¼Ÿå¤ªé™½æœˆäº®ä¸Šå‡æ€éº¼çœ‹ï¼" = "https://open.spotify.com/episode/3xUF3pM1Rt4MRsoKIZdBtH"
"EP33ï½œç”Ÿå‘½éˆæ•¸" = "https://open.spotify.com/episode/5QB60mhAyP9uStDrI89dKf"
"EP32ï½œç«¥å¹´ è²³" = "https://open.spotify.com/episode/1dBoNARjvSa2imCQwwy21v"
"EP31ï½œäº”è¡Œæ±‚è·ä¿¡" = "https://open.spotify.com/episode/65YM7WitH7SPorYPMTdYF4"
"EP30ï½œæˆ‘å€‘ä¸€èµ·éˆæ€§å‡ºæ«ƒå§ï¼Ft.é˜¿å¯¶" = "https://open.spotify.com/episode/54It4UHF387WmH4Xt6YqF6"
"æœ¬é€±é‹å‹¢ï½œ6/5 - 6/11" = "https://open.spotify.com/episode/05usGeaAycfoRdr4PdvRDV"
"EP29ï½œéˆé­‚å¥‘ç´„" = "https://open.spotify.com/episode/1fbUwknT4HCGHocJkNMY5w"
"æœ¬é€±é‹å‹¢ï½œ5/29 - 6/4" = "https://open.spotify.com/episode/7nRUZEwGNxPvwGDa3d0Zu4"
"EP28ï½œç›´ç”·ä½ èªªé˜¿ ft.é‚±æã€é»ƒæ´„" = "https://open.spotify.com/episode/0JRCUtfg2CUdiBnKJcqDmo"
"æœ¬é€±é‹å‹¢ï½œ5/22 - 5/28" = "https://open.spotify.com/episode/0cXI3pySAcjlH0SHbNHYfb"
"Meditationï½œThe Great Soul Sync. ï¼ˆç„¡æ•™å­¸ç‰ˆï¼‰" = "https://open.spotify.com/episode/5Tv8lCtWSwVQxenB8tATqo"

[youtube]
"EP93ï½œç•¶ç†ç§‘å­¸éœ¸å­¸äººé¡åœ– ft.Astor" = "https://www.youtube.com/watch?v=Ryg3zmZ5WWM"
"EP93ï½œç•¶ç†ç§‘å­¸éœ¸å­¸äººé¡åœ– ft.Austor" = "https://www.youtube.com/watch?v=Ryg3zmZ5WWM"
"å®¶å®¶é…’è£œç¿’ç­ #ep88 #shorts" = "https://www.youtube.com/watch?v=f1kQ7sp0E1k"
"è€å¸«æˆ‘çœŸçš„è¦è¡äº†å–” #ep87  #shorts" = "https://www.youtube.com/watch?v=R9GnUXQKqoc"
"è€å¸«å¯æ˜¯QQ #ep87 #shorts" = "https://www.youtube.com/watch?v=2RduF7NWHxM"
"EP92ï½œä¸¹éœ–ç™‚å®¤ å†è¦‹å¤©ä½¿ ft.Bonnie" = "https://www.youtube.com/watch?v=6sP0iDFvr14"
"æŠ±æ­‰çš„éŒ¢éŒ¢ æˆ‘éœ€è¦é€™å€‹é…·æ±è¥¿ #EP87 #shorts" = "https://www.youtube.com/watch?v=rh0bUdhvfZA"
"EP91ï½œéŠ€æ²³è¯é‚¦ä¾†ç£å¯Ÿ" = "https://www.youtube.com/watch?v=cvXwCKkHcQ0"
"EP90ï½œä½ çš„å¤©ä½¿å¥½å¤¥ä¼´ æ…ˆæ‚²å¤©ä½¿è–åœ˜" = "https://www.youtube.com/watch?v=Sv-1Wr_cljw"
"EP89ï½œéˆæ€§æ­æ´²æ—…è¡Œä¹‹å¥³å·«åˆ°åº•åœ¨å“ªè£¡" = "https://www.youtube.com/watch?v=WjB0YN_SElw"
"EP88ä¸¹éœ–èŠå®¤02ï½œå¥‡å¹»æ—…ç¨‹" = "https://www.youtube.com/watch?v=xKUYPQl00Dg"
"è¢ç«èŸ‘ä¹‹å¢“ #EP83 #shorts" = "https://www.youtube.com/watch?v=TxzWCZ6A0sA"
"æ¬¸? #ep83 #shorts" = "https://www.youtube.com/watch?v=NBqj3g7hr7c"
"ç¥çš„é›éŠ #ep82  #shorts" = "https://www.youtube.com/watch?v=3bqBCosET3s"
"æ•²æ•²é–€ğŸ’• #ep82 #shorts" = "https://www.youtube.com/watch?v=iY_emBIsaEA"
"å››éšæ€ªå’–ä¿±æ¨‚éƒ¨ğŸ¤ª #ep82 #shorts" = "https://www.youtube.com/watch?v=EAOLQBJ0-78"
"ä¸¹ä¸¹è€å¸«çš„é›²ç«¯åˆ†äº« #ep81 #shorts" = "https://www.youtube.com/watch?v=sStWZP_Xa8E"
"å–„å“‰å–„å“‰ #ep81 #shorts" = "https://www.youtube.com/watch?v=TSDIf2tAhdg"
"ğŸ¤«#ep80 #shorts" = "https://www.youtube.com/watch?v=g-fAMDCxfGA"
"EP87ï½œä¾†çœ‹çœ‹ç´«å¾®ç©ä»€éº¼ ft.å¤§è€•è€å¸«" = "https://www.youtube.com/watch?v=GXU4NXTT068"
"çœŸé¦™ #ep79 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=JjdSdG7j_KU"
"è€è˜‡å§¬ #ep79 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=QmDu4NX4nxI"
"EP86ï½œå®¶æ—æ’åˆ—" = "https://www.youtube.com/watch?v=XTx_CbvlBTs"
"EP85ï½œä»Šå¤©ä¾†å–åå›‰ï¼" = "https://www.youtube.com/watch?v=Hga20XDDAHY"
"â¤ï¸ #ep78 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=6S_BDRhvBZE"
"æ—é‚Šå”å”èººæ§ğŸ¯#ep78 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=SKXgVOtrh0o"
"ç¼½å…‹å¤ #ep77 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=s3QMHna1YYQ"
"EP84ä¸¹éœ–èŠå®¤01ï½œä¾†è‡ªå¦ä¸€å€‹ä¸–ç•Œçš„æ•…äº‹" = "https://www.youtube.com/watch?v=j1r5tXXQvLA"
"è½é Œç¼½å¸«èªªè©±è½åˆ°ç¡è‘—åˆ°åº•æ˜¯å¤±ç¦®é‚„æ˜¯å°Šé‡å‘¢ï¼ŸğŸ¤£#ep77 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=x4zTo1xqPbA"
"é Œç¼½å“„æ³•ï¼Œä¸ç¡æ£’æ‰“ğŸ’ #ep77 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=NlCgGLAHuZU"
"å°æ‰ğŸ #ep77 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=gQrE48DXxJY"
"é€™æ‰‹â‹¯â‹¯ #ep76 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=F8yo6zYqXTc"
"EP83ï½œLetâ€™sç©ç©é™°é™°å¾·" = "https://www.youtube.com/watch?v=Y3SJPI-Pl8A"
"EP82ï½œç«çš„é­”æ³• ft.æ±Ÿæ±Ÿ" = "https://www.youtube.com/watch?v=1VjUOoznVGU"
"EP81ï½œç´«è‰²ç«ç„°2.0" = "https://www.youtube.com/watch?v=8NXFTGkPHOE"
"EP80ï½œè®“è‰¾è‰çµ²ä¾†æ•™ä½ ç”Ÿå‘½éˆæ•¸" = "https://www.youtube.com/watch?v=TDxJSbbHgHk"
"é‚£ä½åŒå­¸å¾Œä¾†è·‘å»æ¼”æˆ²äº†ğŸ¤£ #ep76 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=Wdw09_Bov8c"
"é‚„æ˜¯æ„›åª½åª½å•¦â¤ï¸ #ep75 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=39L8KSLx1DA"
"çš®åœ¨ç™¢ğŸ† #ep74 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=nexnO52Cw4Q"
"åª½ï¼Œæˆ‘é‚„ç¼ºä¸€é»é ­æœŸâ¤ï¸ #ep74 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=bpJme-n8W84"
"è§€éŸ³ç¤¾ç‰›ç—‡ #ep74 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=U7oxdYEdLPw"
"æ„›è‡ªå·±æ„›éé ­ï¼Ÿ #ep73 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=Q55G89Aidfk"
"EP79ï½œèŠ³é¦™ç™‚æ³•å¤©åä¾†äº† ft.GINA è¨±æ€¡è˜­" = "https://www.youtube.com/watch?v=g4Qx5bBSsgM"
"æˆ‘ä¹Ÿå¯ä»¥ä»˜å‡ºâ¤ï¸#ep73 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=I_96LjTouwQ"
"EP78ï½œé–’èŠé»ƒé‡‘ç´€å…ƒ" = "https://www.youtube.com/watch?v=hSwg6eOdBtE"
"æˆ‘çœ‹äº†ä»€éº¼ğŸŒ #ep72 #è¬ä¾éœ– #é™³å“è±  #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=ot0Od-EDDDU"
"æ­å–œç™¼è²¡ #ep72 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=KQ2qTpzXIlk"
"ä¸‰å¯¶åŸºå› åºåˆ—å·²ä¸Šç·š#ep71 #è¬ä¾éœ– #é™³å“è±  #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=JLK73EkUaPA"
"éƒ½æ˜¯æ¥­éšœå‘€ğŸ˜­ #ep71 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=LD820SuNT_8"
"éœå¿ƒé Œç¼½ ft. é Œç¼½ç™‚ç™’å¸« Ashley æ„›å¸Œ" = "https://www.youtube.com/watch?v=cVMQrN4h6Ck"
"EP77ï½œé Œç¼½å¸« ft. é Œç¼½ç™‚ç™’å¸« Ashley æ„›å¸Œ" = "https://www.youtube.com/watch?v=T5osEvqaTnI"
"éœå¿ƒé Œç¼½-Ashley é Œç¼½æ„›å¸Œ" = "https://www.youtube.com/watch?v=cVMQrN4h6Ck"
"EP77ï½œé Œç¼½å¸« ft.é Œç¼½æ„›å¸Œ Ashley" = "https://www.youtube.com/watch?v=T5osEvqaTnI"
"éœå¿ƒé Œç¼½-Ashley" = "https://www.youtube.com/watch?v=cVMQrN4h6Ck"
"EP77ï½œé Œç¼½å¸« ft.Ashley" = "https://www.youtube.com/watch?v=T5osEvqaTnI"
"EP76ï½œé–‹æ‚Ÿä¸ƒè„ˆè¼ª" = "https://www.youtube.com/watch?v=irLt3-fL_x0"
"EP75ï½œä¸æƒ³é•·å¤§çš„äºº" = "https://www.youtube.com/watch?v=mkPB5WdRXJA"
"EP74ï½œè·Ÿæ¯å¨˜å€‘è«‹å®‰" = "https://www.youtube.com/watch?v=EHb7bdcI6e0"
"EP73ï½œé›æ¹¯é–’èŠ" = "https://www.youtube.com/watch?v=LFNTQItPmGE"
"æ²’äº‹ä¸ç”¨è²·ï¼Œå¡ä½è²·å°±é€šï¼Ÿ #ç¥ä»™è£œç¿’ç­ep70  #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #shorts" = "https://www.youtube.com/watch?v=njvtrLG_nL4"
"éŒ„ä¸€æ•´å¤©é‚„çœŸåªæœ‰é€™å ´ç•«è³ªå‡ºå•é¡ŒğŸ™ˆ #ç¥ä»™è£œç¿’ç­ep70  #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #shorts" = "https://www.youtube.com/watch?v=0muG8PybLjo"
"å·®é»æŠŠå°èƒ–é€¼åˆ°çµ•è·¯ğŸ’ #ç¥ä»™è£œç¿’ç­ep69 #è¬ä¾éœ–  #é™³å“è±  #ä¸¹ä¸¹è€å¸« #shorts" = "https://www.youtube.com/watch?v=HD-ugS7wEE4"
"æ¬¸ä¸å¯èƒ½é€™éº¼å¥½é¨™å§ğŸ«² #ç¥ä»™è£œç¿’ç­ep69 #è¬ä¾éœ–  #é™³å“è± #ä¸¹ä¸¹è€å¸« #shorts" = "https://www.youtube.com/watch?v=8sIraQzvph8"
"EP72ï½œè²¡ç¥çºŒé›†" = "https://www.youtube.com/watch?v=YhNJ2cU0qHE"
"å–œæ€’ç„¡å¸¸ğŸ˜˜ğŸ¤¬ #ep67 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=f4C05SarbvU"
"çªç„¶é–‹ç™¼ä¸€å€‹é½Šè€³çœ‰å‹ #ep66 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=y2jMVdpixiE"
"EP71ï½œå§»ç·£é‚„çœ‹æ¥­åŠ›å¹³è¡¡?!" = "https://www.youtube.com/watch?v=_6Fpu5v4jbk"
"æˆ‘æ„›å¤§å®¶â¤ï¸ #ep67 #è¬ä¾éœ– #é™³å“è±  #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=zmeBqgdflGc"
"å¾ˆåƒæ€ªç¸é›»åŠ›å…¬å¸çš„é–€ #ep68 #è¬ä¾éœ– #é™³å“è±  #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=yRAed5LInE4"
"è€å¸«è¬›è©±è¦å°å¿ƒå…§ #ep66 #é‡Œæ°‘æœå‹™ä¸­å¿ƒ #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=HGZoS64IViw"
"ç•¶å½±ç‰‡æŒæ¡åœ¨è€å…¬æ‰‹ä¸Šæ™‚ğŸ˜ #ep70 #ç°¡å°‘å¹´ #ç¾ä»£å‘½é‹è¨­è¨ˆèª² #ä½æ–¼å…­æŠ˜ #ç¾çœ4000å…ƒèµ· #è¬ä¾éœ– #é™³å“è±  #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=tHr1YY7EDXI"
"EP70ï½œå‘½é‹è¨­è¨ˆç³»ä¸»ä»»ä¾†äº† feat.ç°¡å°‘å¹´" = "https://www.youtube.com/watch?v=gXqkBw9zWxs"
"è¬›è©±å¥½å¥½è¬›M3 #ep66 #è¬ä¾éœ– #é™³å“è± #ä¸¹ä¸¹è€å¸« #ç¥ä»™è£œç¿’ç­ #shorts" = "https://www.youtube.com/watch?v=XK3znu_6gxM"
