"準提佛母祈禱｜四月主題" = "extra"
"EP128 照顧季己就好 #ep128 #shorts" = "extra"
"準提佛母祈禱｜五月主題（請先閱讀說明欄綠勾勾）" = "extra"
"EP128 油腔滑調 #ep128 #shorts" = "extra"
"EP129 細節大師 #ep129 #shorts" = "extra"
"EP129 蒙蔽了雙眼...跟頭腦 #ep129 #shorts" = "extra"
"EP129 偶4小廢物嗚嗚嗚 #ep129 #shorts" = "extra"
"神仙部落 x 希塔療癒 x 小剛老師 #shorts" = "extra"
"EP130 不想換公司 #ep130 #shorts" = "extra"
"EP130 你看見我也看見 #ep130 #shorts" = "extra"
"點食成金｜樓上神秘的安排，開錄第一集竟是補習班錄音的前屋主！" = "extra"
"EP131 靈性潔癖算愛乾淨嗎？ #ep131 #shorts" = "extra"
"EP131 不需要的可以放下 #ep131 #shorts" = "extra"
"EP132 哭哭大賽捨我其誰 #ep132 #shorts" = "extra"
"點食EP2 晨間酒吧黃昏咖 #點食成金 #shorts" = "extra"
"點食EP2 還真的給我喝醉 #點食成金ep2 #shorts" = "extra"
"點食成金EP2｜我不是酒空，只是在Day Drinking，闆娘輕鬆帶壞所有人，是交壞朋友還是自己劣根性太重？一邊酒精一邊咖啡，陷入清醒與迷幻的雙重宇宙，我們還逃得出來嗎？" = "extra"
"Ep132 想哭就該哭 #ep132 #shorts" = "extra"
"準提佛母祈禱｜六月主題 （請先閱讀說明欄綠勾勾）" = "extra"
"EP133 所以不是漂亮的意思囉😡 #ep133 #shorts" = "extra"
"點食成金EP3｜一秒踏進牛宇宙！排山倒海的牛滷料理讓依霖眉頭一皺？！牛控老闆太直男，餐點沒到標語先到！出餐出到夫妻吵架原來是好吃的證明？！" = "extra"
"EP133 有亮說沒亮聽 #ep133 #shorts" = "extra"
"點食EP3 不吃牛的女子該何去何從？ #點食成金 #shorts" = "extra"
"點食EP3 諧音梗與我們的極限拉扯 #點食成金 #shorts" = "extra"
"EP134 一碗水怎麼端平？ #ep134 #shorts" = "extra"
"點食成金EP4｜你這什麼態度！？我這是美麗的態度OK？被好友、甜食這些美好的事物包圍，想不美都難！但就算再美，飲食怪癖也只能冷門不能邪門吧？！" = "extra"
"EP134 斷頭式教育 #ep134 #shorts" = "extra"
"點食成金 EP4 到底今日誰才是大哥！ #點食ep4 #shorts" = "extra"
"點食成金EP4 草莓蒂頭也有這天 #點食ep4 #shorts" = "extra"
"EP135 請多關心身邊人的情況 #ep135 #shorts" = "extra"
"點食成金EP5｜還記不記得小時候的秘密基地？那個讓你盡情伸展心靈、塞滿零食寶物、自由自在的小天地？一起來弎時咖酒，讓這個秘密基地還你原形！" = "extra"
"EP135 水溝蓋還有位置呦！ #ep135 #shorts" = "extra"
"點食成金EP5 真心話大冒險（Ｘ）真心話真心話（Ｏ） #點食ep5 #shorts" = "extra"
"點食成金EP5 不容許反駁 #點食ep5 #shorts" = "extra"
"點食成金EP5｜竟然有枕頭不是拿來睡而是拿來吃的？還有天才不睡到13:14不肯起床？！貪睡鬧鐘引起夫妻失和？！快來 Pillo 一探究竟吧～" = "extra"
"點食成金EP6｜竟然有枕頭不是拿來睡而是拿來吃的？還有天才不睡到13:14不肯起床？！貪睡鬧鐘引起夫妻失和？！快來 Pillo 一探究竟吧～" = "extra"
"EP136 說了你又不開勳 不說你又生氣 #ep136 #shorts" = "extra"
"點食成金EP5 (￣∇￣) #點食ep5" = "extra"
"EP136 還上了不只一次 #ep136 #shorts" = "extra"
"點食成金EP5 不是那種的我可是不吃的呦 #點食ep5 #shorts" = "extra"
"EP137 提款卡遊記 #ep137 #shorts" = "extra"
"準提佛母祈禱｜七月主題（請先閱讀說明欄綠勾勾）" = "extra"
"點食成金EP7｜劇場王子爆笑登場！從車關衰事聊到藝術怪癖、房事秘辛，全程爆點連發！這集千萬不要在辦公室看！" = "extra"
"點食成金EP7 猩猩 強大！ #點食ep7 #shorts" = "extra"
"EP137 彷彿可以瘦十公斤 #ep137 #shorts" = "extra"
"點食成金EP7 死死盯著 #點食ep7 #shorts" = "extra"
"EP138 purple star #ep138 #shorts" = "extra"
"點食成金EP8｜把三分鐘熱度活成不一樣的樣子！她從厭世社畜變身成森林女巫，意外開了間森林系療癒咖啡店！還用塔羅算出依霖對老公索求無度？！丹丹首次公開塔羅占卜，又會算出什麼驚人的未來？！" = "extra"
"EP138｜丹霖聊室：她向月老許願兩個月後，真的遇見命定對象！跨出小小的一步，翻轉整個命運，命運的拼圖就差那一塊！Nana做到啦～" = "extra"
"EP138 命中注定 #ep138 #shorts" = "extra"
"點食成金EP8 根本是露比醬～嗨～ #點食ep8" = "extra"
"EP139｜以為夢想終於實現，卻被現實甩一巴掌，走遍36國，一段從泥淖爬出來的自我救贖 ft.韓" = "extra"
"點食成金EP8 討厭～ #點食ep8 #shorts" = "extra"
"點食成金EP9｜這間咖啡廳讓全台新手父母落淚了，帶娃出門不再像難民！不只有陪玩姊姊讓你能好好吃飯聊天，還能打電動、逛嬰兒用品、音響鑒賞？！" = "extra"
"EP139 義點點興奮 #ep139 #shorts" = "extra"
"EP139 給自己多少理由都不嫌多 #ep139 #shorts" = "extra"
"點食成金EP9 將心比心 #點食ep9 #shorts" = "extra"
"EP139 你是誰～ #ep139 #shorts" = "extra"
"點食成金EP9 Pizza hater #點食ep9 #shorts" = "extra"
"EP140 沒有保險ㄋㄟˊ #ep140 #shorts" = "extra"
"EP140 雲霄飛車 #ep140 #shorts" = "extra"
"EP141 為什麼我都顯化不出來！ #ep141 #shorts" = "extra"
"EP141 沒有人先學會飛 #ep141 #shorts" = "extra"
"EP142｜不可能吧！命盤其實是立體的？紫微斗數還能看見多元宇宙？資訊多到大腦快當機！跟著好久不見的大耕老師，一起在紫微斗數的世界中腦洞大開吧～" = "extra"
"準提佛母祈禱｜八月主題（請先閱讀說明欄綠勾勾）" = "extra"
"EP142 papa? #ep142 #shorts" = "extra"
"EP142 夜觀天象，掐指一算 #ep142 #shorts" = "extra"
"EP143 笑著笑著就哭了 #ep143 #shorts" = "extra"
"EP143 冷鬼 #ep143 #shorts" = "extra"
"EP144 散財童子～ #ep144 #shorts" = "extra"
"EP144 加這輩子八輩子 #ep144 #shorts" = "extra"
"EP145 砸鬼飯碗 #ep145 #shorts" = "extra"
"EP145 看腳本都不敢相信自己的眼睛 #ep145 #shorts" = "extra"
"EP146 符到！ #ep146 #shorts" = "extra"
"準提佛母祈禱｜九月主題（請先閱讀說明欄綠勾勾）" = "extra"
"EP146 斜槓開到辣邊去 #ep146 #shorts" = "extra"
"EP147 我們都是在不斷的學習 #ep147#shorts" = "extra"
"EP145｜丹霖聊室：變裝皇后、SRT療癒師、補教老師、英文口譯、冷氣師傅，竟然全是同一人？讓靈魂順流，不輕易放過每個人生轉變的契機，宇宙的安排其實比你我想的更讚喔！ft.Besu" = "extra"
"EP147｜丹霖聊室：人生轉彎360度，到底是回到原點還是大轉彎？一個害怕靈性的全職媽媽，從靈魂暗夜走了到曼陀羅創作，只因遇見了「高我」，讓她的生活 amazing 大翻轉～ft.DiTi" = "extra"
"EP147 善良的人閃閃發亮 #ep147 #shorts" = "extra"
"EP148｜丹霖聊室：街頭藝人到國際音樂節，在愛河打鼓到站上音樂祭舞台，用音樂找到自己、勇敢追夢，她的非洲鼓夢還在持續進行！現場表演一段即興演奏搭配吟唱，讓主持人們猛獸出閘啦！聽完感覺自己都昇華了呢～" = "extra"
"EP148 雖然快樂是一天，難過是一天，但每天都是一天 #ep148 #shorts" = "extra"
"EP148｜丹霖聊室：Nora現場帶來一段即興演奏搭配吟唱，讓主持人們猛獸出閘啦！街頭藝人到國際音樂節，在愛河打鼓到站上音樂祭舞台～用音樂找到自己、勇敢追夢，她的非洲鼓夢還在持續進行！" = "extra"
"EP148 誰舉手了🤣 #e148 #shorts" = "extra"
"EP148 天籟吧 #ep148 #shorts" = "extra"
"EP149｜丹霖聊室：竟然！故事精彩到需要分成上下集啦～富二代金童到落難王子，歷經跌宕人生後，把破碎的自己重新拼出一幅美麗的風景！（上集）ft.Sam" = "extra"
"EP149 高中老師斜槓身心靈老蘇 #ep149 #shorts" = "extra"
"EP149 直接打醒 #ep149 #shorts" = "extra"
"【新家開箱～上集】這到底是什麼樣的開箱，竟然可以從依霖懷孕開始拖到孩子都上小學了才發表！？只能說等待是值得的，一起來看看這個充滿細節的 Dream house 吧！" = "extra"
"EP150 誒誒誒莫須有的罪名🤣 #ep150 #shorts" = "extra"
"【新家開箱～下集】女明星私領域大公開，變美的關鍵就在這裡！獨家分享自地自建七年辛酸血淚史，舉凡最值得、最後悔、最冤枉、最任性、最實用的心得，一次通通報你知！" = "extra"
"EP150 也請記得善待自己 #ep150 #shorts" = "extra"
"準提佛母祈禱 十月主題（請先閱讀說明欄）｜Prayer to Seven-Koṭi-Buddha-Mother Cundi for October" = "extra"
"EP151 物是人非但羈絆還在 #ep151 #shorts" = "extra"
"EP151 又給你們學到一招🥸 #ep151 #shorts" = "extra"
"EP152 一陣頭暈 #ep152 #shorts" = "extra"
"EP152 配得感的議題 #ep152 #shorts" = "extra"
"EP153 928傳統 #ep153 #shorts" = "extra"
"EP153 嚇鼠 #ep153 #shorts" = "extra"
"EP154 不知道標題怎麼下🥸 #ep154 #shorts" = "extra"
"EP154 一輩子學不完就留到下輩子學 #EP154 #shorts" = "extra"
"EP155 塞翁失馬 焉知非福？ #ep155 #shorts" = "extra"
"EP155 所以牠是在氣小綠的名字還是歌聲？ #ep155 #shorts" = "extra"
"EP156 到底是看很開還是想很開？ #ep156 #shorts" = "extra"
