"蒙古人都會養老鷹？ #shorts #蒙古 #草原" = "extra"
"凱莉覺得諮商像在工作 #shorts #心理 #諮商" = "extra"
"餵老鼠喝高粱 #林文鑫教授 #CMU995 #995益生菌" = "extra"
"百靈果NEWS｜精蟲賽跑，凱莉花錢看中國反轉片！台灣成為第52州會發生什麼事？" = "extra"
"The KK Show 307 - 聊聊關稅戰 IEObserve國際經濟觀察 雕大@IEObserve" = "extra"
"川普瘋了？預測關稅戰未來走向 ft.@IEObserve #川普 #財經 #中國" = "extra"
"日本年輕人躺平讓台積電很困擾 ft.@IEObserve #台積電 #國際新聞 #財經" = "extra"
"讀書會：菁英媽媽想上班 ep1" = "extra"
"電動車墳場？中國電動車超越日本跟德國的地方 ft.@IEObserve #電動車 #財經 #中國" = "extra"
"The KK Show 308 - 阿滴有很多話要說 @rayduenglish" = "extra"
"阿滴希望理性討論脆上爭議 ft.@rayduenglish #threads #炎上 #溝通" = "extra"
"The KK Show 309 - 想當脆王 呱吉 @FroggyChiu" = "extra"
"台灣終於開始要流行陰謀論了？ ft.呱吉 @FroggyChiu #threads #陰謀論 #邱威傑" = "extra"
"脆上生態很可怕 ft.呱吉 ⁨@FroggyChiu⁩ #threads #社群媒體 #邱威傑" = "extra"
"呱吉喜歡被罵 ft.呱吉 ⁨@FroggyChiu⁩ #threads #shorts #邱威傑" = "extra"
"百靈果NEWS｜ 美國失智皇帝拜登？外國網紅開箱北韓馬拉松，7000萬美金藝術品流標！" = "extra"
"呱吉嗆Jim專場難看 ft.呱吉 ⁨@FroggyChiu⁩ #threads #程建評 #邱威傑" = "extra"
"The KK Show 310 - 立法委員 沈伯洋 @PumaShen" = "extra"
"在立院打架會遇到哪些事情？ ft.@PumaShen #立法院 #政治#議會" = "extra"
"認知作戰不分黨派？政治人物如何避免越走越極端 ft.⁠@PumaShen #網路 #認知作戰 #政治" = "extra"
"菁英也會被詐騙 ｜讀書會 Scam Inc ep1、2" = "extra"
"政治人物很雙面？私底下跟議會上截然不同 ft.@PumaShen #政治 #立法院 #朝野協商" = "extra"
"The KK Show 311 - 成人水療中心 瑞恩 @ThisisRayRay" = "extra"
"澳洲“水療”中心的爺爺奶奶好會玩 ft.@ThisisRayRay #喜劇 #澳洲 #旅遊" = "extra"
"澳洲“水療”中心 pt2 -水池髒髒 ft.@ThisisRayRay #喜劇 #澳洲 #旅遊" = "extra"
"澳洲“水療”中心 pt3 -八字奶奶的奶奶 ft.@ThisisRayRay #喜劇 #澳洲 #旅遊" = "extra"
"女生不准那麼戀愛腦｜交友詐騙" = "extra"
"The KK Show 312 - 深入烏克蘭的台灣記者 致盺 @boohowis" = "extra"
"誰說發ep一定要唱歌，嗨就好了！" = "extra"
"家醜就是要外揚 ft.@ThisisRayRay #長輩 #情緒價值 #療傷" = "extra"
"薔薔申請美簽慘遭拒絕！＃卡米地＃薔薔＃百靈果週二夜" = "extra"
"The KK Show 312 - 深入烏克蘭的台灣記者 致昕@boohowis" = "extra"
"戰爭下烏克蘭的夜生活 ft.@boohowis #國際新聞 #烏克蘭 #戰爭" = "extra"
"烏克蘭的獨角獸部隊 ft. ⁨@boohowis⁩ #國際新聞 #烏克蘭 #lgbt" = "extra"
"用抖音看新聞是未來趨勢？ ft. ⁨@boohowis⁩ #國際新聞 #報導 #社群媒體" = "extra"
"日本老人開車爆衝事故 ft.李明賢 #交通事故 #行人地獄 #高齡駕駛" = "extra"
"有出國沒有考察的官員 ft.李明賢 #交通事故 #行人地獄 #高齡駕駛" = "extra"
"走在路上開始有汽車會禮讓 ft.李明賢 #交通事故 #行人地獄 #道路平權" = "extra"
"圓燈難題 ft.李明賢 #交通事故 #行人地獄 #交通" = "extra"
"The KK Show 314 - KID 林柏昇 @kid7fat" = "extra"
"百靈果NEWS｜川普參戰，研究顯示用AI會變笨，電影推薦《造山者》" = "extra"
"KID是百靈果的粉絲？！（某些層面來講） ft. ⁨@kid7fat⁩ #藝人 #綜藝 #circus" = "extra"
"壁虎沙西米？以前綜藝節目超級瘋 ft.@kid7fat #綜藝 #搞笑 #KID" = "extra"
"台灣早期藝人其實很窮? ft.@kid7fat #綜藝 #搞笑 #KID" = "extra"
"台灣新聞可以信嗎？ ft. ⁨@kid7fat⁩ #綜藝 #搞笑 #新聞" = "extra"
"愛莉莎莎上百靈果被欺負 ft.@alisasa_official #網紅 #炎上 #搞笑" = "extra"
"The KK Show 315 - 愛莉莎莎 @alisasa_official" = "extra"
"爭議型網紅其實有在避免炎上 ft. ⁨@alisasa_official⁩ #網紅 #炎上 #爭議" = "extra"
"愛莉莎莎教瑜伽(凱莉在放空) ft. ⁨@alisasa_official⁩ #課程 #瑜珈 #脈輪" = "extra"
"瑜伽可以幫助性生活? ft. ⁨@alisasa_official⁩ #瑜珈 #能量 #搞笑" = "extra"
"好萊塢女星整壞沒關係？ ft.陳昱璁醫師 #醫美 #整形 #藝人" = "extra"
"把鮭魚Ｏ打臉上？鮭魚好犧牲 ft.陳昱璁醫師 #醫美 #麗珠蘭 #精緻女孩" = "extra"
"不重要的扶輪社冷知識 ft.陳昱璁醫師 #諧教 #交友 #諧音梗 #醫生" = "extra"
"The KK Show 317 - 變成好萊塢大咖 Atsuko Okatsuka @AtsukoComedy （CC中文字幕）" = "extra"
"百靈果飛去美國找喜劇巨星Atsuko ft.@AtsukoComedy #comedy #comedyshorts #搞笑" = "extra"
"勇敢承認自己是台灣人！ ft.@AtsukoComedy #comedy #standup #taiwan" = "extra"
"最吵v.s.最安靜國家排名 ft.@AtsukoComedy #comedy #ranking #taiwan" = "extra"
"最吵vs最安靜國家排名 ft.@AtsukoComedy #comedy #ranking #taiwan" = "extra"
"粉絲是偏激川普支持者怎麼辦？ ft.@AtsukoComedy #comedy #lgbt #standupcomedy" = "extra"
"The KK Show 318 - 衛生紙不夠用 歐耶 @teacherOya" = "extra"
"歐耶跟豪平到澳洲的特殊體驗 ft.@teacherOya #澳洲 #搞笑 #旅遊" = "extra"
"連博恩都跑來關心的炎上 ft.@teacherOya #走鐘獎 #喜劇 #炎上" = "extra"
"美女因為狐臭被甩 ft.陳昱璁院長 #醫美 #狐臭 #miradry" = "extra"
"The KK Show 319 - 即刻救援 Bump @bumpbro" = "extra"
"詐騙猖獗！罰重一點有用嗎？ ft. @bumpbro #詐騙 #罰款 #社會議題" = "extra"
"被騙去柬埔寨救人? ft. @bumpbro #反詐騙 #國際新聞 #柬埔寨" = "extra"
"到現在還有人被騙去柬埔寨？ ft. @bumpbro #國際新聞 #ngo #社會" = "extra"
"聊聊大罷免" = "extra"
"政府該如何幫助詐騙救援？ ft. @bumpbro #政府 #國際新聞 #柬埔寨" = "extra"
"The KK Show 320 - Do Man Ian @TheDoDoMen" = "extra"
"The KK Show 320 - 鐵人精神 The Do Man Ian @TheDoDoMen" = "extra"
"Ian、Eric傻傻分不清 ft.@TheDoDoMen #搞笑 #podcast #comedy" = "extra"
"凱莉沒有鐵人精神 ft.@TheDoDoMen #鐵人三項 #運動 #馬拉松" = "extra"
"芬蘭的運動是獵俄羅斯人？ ft. ⁨@TheDoDoMen⁩ #鐵人三項 #運動 #冬季兩項" = "extra"
"Ian超愛面談員工 ft. ⁨@TheDoDoMen⁩ #成功學 #企業 #員工管理" = "extra"
"蔡阿嘎夜衝日本二伯爆氣 ft. @TsaiAGa ＃日本 ＃夫妻 ＃蔡阿嘎" = "extra"
"The KK Show 321 - 雙語學校 Peggy @peggyfoshow" = "extra"
"好想看凱莉躺在地上🔥 @TsaiAGa #育嬰 #podcast #蔡阿嘎" = "extra"
"熱到Aaron爆氣的錄音 ft.@peggyfoshow #雙語學校 #度假 #旅遊" = "extra"
"《直播》百靈果股東會（聊天室提問會員限定）" = "extra"
"《直式》百靈果股東大會" = "extra"
"Peggy覺得他的中文講得很標準 ft. @peggyfoshow #雙語 #英文 #發音" = "extra"
"Peggy一直被小孩嗆 ft.@peggyfoshow #podcast #老師 #葡萄牙" = "extra"
"Peggy不知道一年有幾周 ft.@peggyfoshow #podcast #冷知識 #搞笑" = "extra"
"《直式直播》被滲透的百靈果？ feat 王婉諭" = "extra"
"《直播》被滲透的百靈果？ feat 王婉諭 [會員專屬聊天室]" = "extra"
"清大教授怎麼看日本福島事件 ft.葉宗洸教授 #核能 #公投 #福島" = "extra"
"台灣醫師對現在健保制度的不滿 ft.田醫師 • KKSHOW精華" = "extra"
"副局長居然是CIA間諜？ ft.葉宗洸" = "extra"
"百靈果NEWS｜中國領導顛覆者聯盟對抗美地，中國政府滲透全世界的網路，人類憋氣超越海豚" = "extra"
"一起珍惜台灣醫護人員 ft.田知學醫師 #醫療 #健保 #醫院" = "extra"
"《直播》2026你還會投民進黨嗎？ feat cheap [會員專屬聊天室]" = "extra"
"《直播》2026你還會投民進黨嗎？ feat cheap [直式]" = "extra"
"台灣健保在羞辱醫生？ ft.田知學醫師 #醫療 #健保 #醫院" = "extra"
"音樂劇導演在美國只能演移民？ ft.曾慧誠導演 • KKSHOW精華" = "extra"
"40歲跳脫舒適圈- 可若夫 Christina" = "extra"
"美國急診室嚇到台灣醫師 ft.田知學醫師 #醫療 #健保 #醫院" = "extra"
"40歲跳脫舒適圈，創業十年締造上億業績- 可若夫 Christina" = "extra"
"凱莉唱歌唱到哭 ft.阿拉斯 • KKSHOW精華" = "extra"
"台灣導演去美國只能演非法移民？ ft.曾慧誠導演 #百老匯 #舞台劇 #戲劇" = "extra"
"凱莉不小心騷擾女員工？ #社會議題 #職場 #職場生存" = "extra"
"《直式直播》2026你還會投民眾黨嗎 feat. 不禮貌鄉民團" = "extra"
"《直播會員聊天室》2026你還會投民眾黨嗎 feat. 不禮貌鄉民團" = "extra"
"台灣藝術家其實不用這麼窮 ft.曾慧誠導演 #喜劇 #舞台劇 #戲劇" = "extra"
"The KK Show 326 - 中國電動車產業內部 Maureen" = "extra"
"原住民會遇到的刻板印象 ft.阿拉斯 #原住民文化 #阿嘟主義 #石板屋" = "extra"
"The KK Show 326 - 中國電動車產業內幕Maureen" = "extra"
"凱莉唱歌唱到哭 ft.阿拉斯 #唱歌 #阿嘟主義 #張惠妹" = "extra"
"魯凱族爸媽談戀愛像在饒舌對戰 ft.阿拉斯 #原住民文化 #阿嘟主義 #饒舌" = "extra"
"爸媽談戀愛像在饒舌對戰 ft.阿拉斯 #原住民文化 #阿嘟主義 #饒舌" = "extra"
"特斯拉每台都長不一樣？ ft.Maureen • KKSHOW精華" = "extra"
"The KK Show 327 - 嚎哮排演 @haoxhsiaotroupe7483" = "extra"
"《直播會員聊天室》百靈果call in" = "extra"
"《直式直播》百靈果call in" = "extra"
"傳產難經營？老闆想改做神像 ft.Maureen #汽車 #傳統產業 #經濟" = "extra"
"直播精華：凱莉社會性死亡" = "extra"
"特斯拉是汽車界的快時尚？ ft.Maureen #特斯拉 #電動車 #新創" = "extra"
"百靈果跟呱吉世紀大和解？ ft.@FroggyChiu #炎上 #凱莉別哭 #呱吉別生氣" = "extra"
"韓國職場很性別歧視？ ft.Maureen #韓國 #文化 #國際" = "extra"
"每個演員上台前的小動作 ft.@haoxhsiaotroupe7483 • KKSHOW精華" = "extra"
"藝術大學不食人間煙火？ ft.@haoxhsiaotroupe7483 #舞台劇 #北藝大 #搞笑" = "extra"
"演員上台前的中二小儀式 ft. ⁨@haoxhsiaotroupe7483⁩ #舞台劇 #演員 #搞笑" = "extra"
"演員內褲不夠穿？ ft. ⁨@haoxhsiaotroupe7483⁩ #舞台劇 #戲劇 #搞笑" = "extra"
"林森北美食與酒店離奇小故事 ft.酒店經紀Sky • KKSHOW精華" = "extra"
"林森北必吃美食是什麼? ft.Sky #林森北路 #美食 #炸雞" = "extra"
"The KK Show 320 - 印度聽眾 Akshay" = "extra"
"酒店離奇小故事!凱莉教大家怎麼變螢火蟲 ft.Sky #林森北路 #獵奇 #團康遊戲" = "extra"
"《直播會員聊天室》極端言論是誰的錯 feat. 林辰" = "extra"
"每個職業都有心酸處 ft.Sky #共享單車男 #經紀 #林森北路" = "extra"
"《直式》極端言論是誰的錯 feat. 林辰" = "extra"
"百靈果受邀去中國玩？" = "extra"
"奶奶誤入：到底是什麼偉大的表演？" = "extra"
"百靈果挑戰美國很紅的後倒信任遊戲 #信任 #遊戲 #接住" = "extra"
"The KK Show 330 - 馬來西亞男子天團? 3P @ThreeeP" = "extra"
"印度婚禮騎大象？有錢人婚禮超級扯 • KKSHOW精華" = "extra"
"喜歡吃牛肉麵的印度人？打破刻板印象 ft.印度聽眾Akshay #文化 #印度 #牛肉" = "extra"
"印度有錢人結婚送小島?貧富差距極大的社會 ft.印度聽眾Akshay #文化 #印度 #婚禮" = "extra"
"寶萊塢演員被當神崇拜！文化衝擊 ft.印度聽眾Akshay #文化 #印度 #娛樂圈" = "extra"
"100萬人的印度造勢大會有廁所嗎？ ft.印度聽眾Akshay #文化 #印度 #選舉" = "extra"
"Ken回嗆中國酸民" = "extra"
"百靈果NEWS｜花蓮光復鄉現在還需要什麼，講話太極端被拒絕簽證，AI影片引爆中國男人的焦慮" = "extra"
"The KK Show 331 - 酒後亂性感 Kimberly @itsKimberleyChen" = "extra"
"The KK Show 331 - 酒後亂性感 Kimberly @itsKimberleyChen (CC AI中文字幕)" = "extra"
"馬來西亞\"唯一\"的華人唱跳男團 ft.@ThreeeP • KKSHOW精華" = "extra"
"The KK Show 331 - 酒後亂性感 陳芳語 Kimberley （有CC中文字幕）@itsKimberleyChen" = "extra"
"馬來西亞偶像男子天團(?) ft.@ThreeeP #偶像 #唱跳 #流行" = "extra"
"馬來西亞每年出的新年歌比台灣多？ ft.@ThreeeP #馬來西亞 #農曆新年 #華人" = "extra"
"預告｜The KK Show 332 - 台灣有沒有連續殺人魔？犯罪心理學教授 戴伸峰" = "extra"
"陳芳語的IG照片開始變得不一樣！ ft.@itsKimberleyChen (CC中文字幕) • KKSHOW精華" = "extra"
"女歌手玩交友軟體會處處碰壁？ ft.@itsKimberleyChen #感情 #交友 #兩岸" = "extra"
"吃素的人可以吃自己的肉嗎？ ft.@itsKimberleyChen #飲食 #素食 #搞笑" = "extra"
"男生為什麼都不道歉? ft.@itsKimberleyChen #感情 #愛情 #關係經營" = "extra"
"如何跟伴侶溝通性事問題？￼feat.紅犀牛" = "extra"
"氣！氣！氣！有沒有人也遇過這種事" = "extra"
"預告｜The KK Show 333 - 不要變成自己討厭的大人 兒童職能治療師 黃暐恬" = "extra"
1103newsB = "extra"
"不同地區流行不同的犯罪型態？ ft.犯罪心理學教授 戴伸峰 • KKSHOW精華" = "extra"
"台灣社會很情勒其實也有好處 ft.戴伸峰教授 #情緒勒索 #專家 #社會" = "extra"
"鄰居很常在煲湯？香港獨特的犯罪樣態 ft.戴伸峰教授 #香港 #案件 #社會" = "extra"
"犯罪心理揭秘！課程內40個讓你大開眼界的案例 ft.戴伸峰教授 #心理 #專家 #社會" = "extra"
"川普一句話就讓大家崩潰 #trump #tariffs" = "extra"
"預告｜The KK Show 334 - 吳宗憲 @jackywusofficialchannel9062" = "extra"
"綜藝天王想來百靈果好好講話 ft.@jackywusofficialchannel9062 #吳宗憲 #綜藝 #演藝圈" = "extra"
"黑的東西才好吃～" = "extra"
"The KK Show 334 - 吳宗憲 @jackywusofficialchannel9062" = "extra"
"腦波檢測成功網紅的必備特質 ft.兒童職能治療師黃暐恬 • KKSHOW精華" = "extra"
"先讓Ken焦慮 再測他腦波 ft.KidPro兒童發展教育團隊 #情緒 #焦慮 #腦波" = "extra"
"《直播會員聊天室》單飛的更生人 feat.栗子" = "extra"
"The KK Show 335 - 單飛的更生人 Lizi栗子 @Lizi栗子" = "extra"
"《直式直播》單飛的更生人 feat.栗子" = "extra"
"喜劇演員都不喜劇演員了 #comedy #comedian" = "extra"
"預告｜The KK Show 336 - 泰國監獄回來的Jason" = "extra"
"百靈果NEWS｜真人版魷魚遊戲，美國人去天安門直播被公安查手機，在野黨跑票被支持者罵爆" = "extra"
"吳宗憲痛批台灣媒體“變壞了”！都是因為這個原因 ft.@jackywusofficialchannel9062 • KKSHOW精華" = "extra"
"美國萬聖節怎麼玩? Ken原來超膽小 #美國 #萬聖節 #文化" = "extra"
"吳宗憲不忍了!竟為了這個原因飆罵台灣媒體!!?? ft.吳宗憲 #新聞 #狗仔 #媒體" = "extra"
